Repository ral-facilities/scigateway, pull requests merged in 2021-09, with the labels that each got.

#761 Consistent theme across all pages #760
  src/state/middleware/scigateway.middleware.test.tsx
  src/state/middleware/scigateway.middleware.tsx
Labels: bug, MVP

#767 Added the alt text to homepage images from the default.json file #753
  public/res/default.json
  src/homePage/__snapshots__/homePage.component.test.tsx.snap
  src/homePage/homePage.component.tsx
Labels: bug

#764 Logo dynamically changes based on currently loaded plugin #739
  src/mainAppBar/__snapshots__/mainAppBar.component.test.tsx.snap
  src/mainAppBar/mainAppBar.component.test.tsx
  src/mainAppBar/mainAppBar.component.tsx
Labels: enhancement

#769 Modified the mainAppBar component to show the plugin's logo on first load
  src/mainAppBar/__snapshots__/mainAppBar.component.test.tsx.snap
  src/mainAppBar/mainAppBar.component.test.tsx
  src/mainAppBar/mainAppBar.component.tsx
Labels: bug
