Repository ral-facilities/scigateway, pull requests merged in 2021-11, with the labels that each got.

#798 Some contrast fixes #795
  src/contactPage/__snapshots__/contactPage.component.test.tsx.snap
  src/helpPage/__snapshots__/helpPage.component.test.tsx.snap
  src/loginPage/loginPage.component.tsx
  src/theming.tsx
  src/tour/__snapshots__/tour.component.test.tsx.snap
  src/tour/tour.component.test.tsx
  src/tour/tour.component.tsx
Labels: accessibility

#802 Add overrides for year/month selector colours in date pickers (#795)
  src/contactPage/__snapshots__/contactPage.component.test.tsx.snap
  src/helpPage/__snapshots__/helpPage.component.test.tsx.snap
  src/theming.tsx
Labels: accessibility

#804 Override current day colour in dark mode (#795)
  src/theming.tsx
Labels: accessibility

#805 fixing the error colour for form labels #803
  src/contactPage/__snapshots__/contactPage.component.test.tsx.snap
  src/helpPage/__snapshots__/helpPage.component.test.tsx.snap
  src/theming.tsx
Labels: accessibility

#807 changed footer bar colour #806
  src/footer/footer.component.tsx
Labels: accessibility

#809 Fix navigation drawer list structure (#808)
  src/navigationDrawer/__snapshots__/navigationDrawer.component.test.tsx.snap
  src/navigationDrawer/navigationDrawer.component.tsx
Labels: accessibility

#811 The 404 pages in dark mode don't have enough contrast #810
  src/logoutPage/__snapshots__/logoutPage.component.test.tsx.snap
  src/logoutPage/logoutPage.component.test.tsx
  src/logoutPage/logoutPage.component.tsx
  src/pageNotFound/__snapshots__/pageNotFound.component.test.tsx.snap
  src/pageNotFound/pageNotFound.component.test.tsx
  src/pageNotFound/pageNotFound.component.tsx
  src/routing/__snapshots__/authorisedRoute.component.test.tsx.snap
Labels: accessibility

#812 Add overrides for role selector (#795)
  src/theming.tsx
Labels: MVP, accessibility

#814 adding aria labels to the login page #813
  src/loginPage/__snapshots__/loginPage.component.test.tsx.snap
  src/loginPage/loginPage.component.tsx
Labels: accessibility

#819 High contrast modes and improve theme customisation #795
  public/res/default.json
  src/contactPage/__snapshots__/contactPage.component.test.tsx.snap
  src/contactPage/contactPage.component.tsx
  src/cookieConsent/cookieConsent.component.tsx
  src/cookieConsent/cookiesPage.component.tsx
  src/footer/footer.component.tsx
  src/helpPage/__snapshots__/helpPage.component.test.tsx.snap
  src/helpPage/helpPage.component.tsx
  src/homePage/homePage.component.tsx
  src/loginPage/loginPage.component.tsx
  src/logoutPage/logoutPage.component.tsx
  src/mainAppBar/__snapshots__/mainAppBar.component.test.tsx.snap
  src/mainAppBar/mainAppBar.component.test.tsx
  src/mainAppBar/mainAppBar.component.tsx
  src/notifications/scigatewayNotification.component.tsx
  src/pageNotFound/pageNotFound.component.tsx
  src/state/actions/scigateway.actions.test.tsx
  src/state/actions/scigateway.actions.tsx
  src/state/middleware/scigateway.middleware.test.tsx
  src/state/middleware/scigateway.middleware.tsx
  src/state/reducers/scigateway.reducer.test.tsx
  src/state/reducers/scigateway.reducer.tsx
  src/state/scigateway.types.tsx
  src/state/state.types.tsx
  src/theming.tsx
  src/tour/__snapshots__/tour.component.test.tsx.snap
  src/tour/tour.component.tsx
Labels: enhancement, accessibility

#823 Feature/configurable logo #786
  public/settings.example.json
  src/mainAppBar/__snapshots__/mainAppBar.component.test.tsx.snap
  src/mainAppBar/mainAppBar.component.tsx
  src/state/actions/scigateway.actions.test.tsx
  src/state/actions/scigateway.actions.tsx
  src/state/reducers/scigateway.reducer.test.tsx
  src/state/reducers/scigateway.reducer.tsx
  src/state/scigateway.types.tsx
  src/state/state.types.tsx
Labels: enhancement, MVP

#827 Make date picker placeholder the same as the search box (#824)
  src/contactPage/__snapshots__/contactPage.component.test.tsx.snap
  src/helpPage/__snapshots__/helpPage.component.test.tsx.snap
  src/theming.tsx
Labels: MVP, accessibility
