Repository ral-facilities/scigateway, pull requests merged in 2022-02, with the labels that each got.

#925 Added the new message suggested in the issue #914
  src/loginPage/loginPage.component.test.tsx
  src/loginPage/loginPage.component.tsx
Labels: enhancement, MVP

#959 making the nav drawer logo configurable #941
  public/settings.example.json
  src/cookieConsent/__snapshots__/cookieConsent.component.test.tsx.snap
  src/cookieConsent/cookieConsent.component.tsx
  src/helpPage/__snapshots__/helpPage.component.test.tsx.snap
  src/index.css
  src/mainAppBar/mainAppBar.component.tsx
  src/navigationDrawer/navigationDrawer.component.test.tsx
  src/navigationDrawer/navigationDrawer.component.tsx
  src/state/actions/scigateway.actions.test.tsx
  src/state/actions/scigateway.actions.tsx
  src/state/reducers/scigateway.reducer.test.tsx
  src/state/reducers/scigateway.reducer.tsx
  src/state/scigateway.types.tsx
  src/state/state.types.tsx
  src/theming.tsx
Labels: enhancement

#929 Added loading indicator to show progress when delay in showing option
  src/loginPage/loginPage.component.test.tsx
  src/loginPage/loginPage.component.tsx
Labels: enhancement, MVP

#967 Navigation drawer logo is defined by width instead of the height #964
  src/navigationDrawer/navigationDrawer.component.tsx
Labels: bug, MVP

#966 Changing the min-width to work correctly with card view #965
  src/index.css
Labels: bug, MVP
