Repository ral-facilities/scigateway, pull requests merged in 2022-05, with the labels that each got.

#1044 Preventing app bar from opening nav drawer on failed login attempt #999
  cypress/integration/login.spec.ts
  cypress/integration/scigateway_frontend_spec.tsx
  src/mainAppBar/__snapshots__/mainAppBar.component.test.tsx.snap
  src/mainAppBar/mainAppBar.component.test.tsx
  src/mainAppBar/mainAppBar.component.tsx
  src/state/reducers/scigateway.reducer.tsx
Labels: bug

#1050 Homepage accessible regardless of login status #1049
  cypress/integration/login.spec.ts
  src/mainAppBar/mainAppBar.component.tsx
  src/routing/__snapshots__/authorisedRoute.component.test.tsx.snap
  src/routing/authorisedRoute.component.test.tsx
  src/routing/authorisedRoute.component.tsx
  src/state/actions/scigateway.actions.tsx
Labels: enhancement, MVP

#1026 Organise dev and prod dependencies
  package.json
Labels: dependencies
