Repository ral-facilities/scigateway, pull requests merged in 2022-01, with the labels that each got.

#898 Homepage redesign tweaks #897
  public/res/default.json
  src/footer/__snapshots__/footer.component.test.tsx.snap
  src/footer/footer.component.tsx
  src/helpPage/__snapshots__/helpPage.component.test.tsx.snap
  src/homePage/__snapshots__/homePage.component.test.tsx.snap
  src/homePage/homePage.component.tsx
  src/loginPage/loginPage.component.tsx
  src/mainAppBar/__snapshots__/userProfile.component.test.tsx.snap
  src/mainAppBar/mainAppBar.component.tsx
  src/mainAppBar/userProfile.component.tsx
  src/navigationDrawer/navigationDrawer.component.tsx
  src/notifications/notificationBadge.component.tsx
  src/theming.tsx
Labels: enhancement

#905 Changing the toast colours #825
  src/index.css
Labels: accessibility

#911 Apply theming changes (#910)
  src/helpPage/__snapshots__/helpPage.component.test.tsx.snap
  src/theming.tsx
Labels: enhancement, MVP

#913 Remove storybook #908
  .github/dependabot.yml
  .gitignore
  .storybook/addons.js
  .storybook/config.js
  .storybook/main.js
  package.json
  src/stories/cookieConsent.stories.tsx
  src/stories/cookiesPage.stories.tsx
  src/stories/homepage.stories.tsx
  src/stories/index.js
  src/stories/loginPage.stories.tsx
  src/stories/mainAppBar.stories.tsx
  src/stories/navigationDrawer.stories.tsx
  src/stories/notification.stories.tsx
  src/stories/notificationBadge.stories.tsx
  src/stories/pageNotFound.stories.tsx
  src/stories/preloader.stories.tsx
  src/stories/storybookResourceStrings.tsx
  src/stories/tour.stories.tsx
  src/stories/utils.tsx
  yarn.lock
Labels: dependencies

#920 Reset error message after failure to login and navigating away (#915)
  cypress/integration/login.spec.ts
  src/loginPage/loginPage.component.test.tsx
  src/loginPage/loginPage.component.tsx
  src/state/actions/scigateway.actions.test.tsx
  src/state/actions/scigateway.actions.tsx
  src/state/reducers/scigateway.reducer.test.tsx
  src/state/reducers/scigateway.reducer.tsx
  src/state/scigateway.types.tsx
Labels: bug, MVP

#919 Make menu open on site load and fix colour of user avatar (#904)
  cypress/integration/login.spec.ts
  cypress/integration/scigateway_frontend_spec.tsx
  src/homePage/__snapshots__/homePage.component.test.tsx.snap
  src/homePage/homePage.component.tsx
  src/mainAppBar/__snapshots__/mainAppBar.component.test.tsx.snap
  src/mainAppBar/__snapshots__/userProfile.component.test.tsx.snap
  src/mainAppBar/mainAppBar.component.test.tsx
  src/mainAppBar/mainAppBar.component.tsx
  src/mainAppBar/userProfile.component.tsx
Labels: enhancement, MVP
